# Generated by Django 2.2.12 on 2024-10-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_accuracy_history_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='koreanword',
            name='level',
            field=models.IntegerField(default=10),
        ),
    ]
