# Generated by Django 2.2.12 on 2024-10-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_koreanword_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuracy',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
