name: CI-CD Workflow

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: autoneeip/adrien_project_korean:latest

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build And Push Docker Image
        run: |
          docker buildx build -t $DOCKER_REGISTRY --progress plain --platform linux/amd64,linux/arm/v7,linux/arm64 --push .
